In [1]:
import numpy as np
import tensorflow as tf

/Users/zhampel/py-venv/python3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Right-Angle Matrix Rotations

The $90^{\circ}$ rotation of an $N \times N$ matrix $K$ can accomplished via the following matrix operation:

$$
R(\theta=90^{\circ}) \, K = K^{T} \, \overset{\nearrow}{I}
$$

where $\overset{\nearrow}{I}$ is the anti-diagonal or **minor diagonal** $N \times N$ identity matrix:

$$
\overset{\nearrow}{I}(i,N-i) =
\begin{cases}
  1 \, \forall \, i, \\
  0 \, \text{otherwise}
\end{cases}
$$

# Minor Diagonal

Generate matrix with minor diagonal containing all ones via swap.

In [2]:
def minor_eye(dim=3):
    matrix = np.zeros(shape=(dim,dim), dtype='float32')
    for i in range(dim):
        matrix[i][dim-i-1] = 1.
            
    return matrix

In [4]:
print('Minor Diagonal Identity:\n', minor_eye(dim=3))

Minor Diagonal Identity:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# TensorFlow Eval

Make a graph with placeholders for generic matrices.

In [6]:
# Define Placeholders with variable sizes
g = tf.Graph()

with g.as_default():
    tf_k = tf.placeholder(tf.float32,
                          shape=[None, None],
                          name='tf_k')
    
    tf_e = tf.placeholder(tf.float32,
                          shape=[None, None],
                          name='tf_e')
    
    w_rot = tf.matmul(tf_k, 
                      tf_e, 
                      transpose_a=True,
                      name='w_rot')

# Run Rotation

Start with random integer square matrix, rotate by 90 degress.

In [7]:
dim = 5
with tf.Session(graph=g) as sess:
    kernel = np.random.randint(low=0, high=10, 
                               size=(dim, dim))
    
    print('Kernel shape: ', kernel.shape)
    print('Original Matrix:\n', sess.run(tf_k, feed_dict={tf_k : kernel}))
    
    meye = minor_eye(dim=dim)

    print('Rotated Matrix:\n', sess.run(w_rot, feed_dict={tf_k : kernel, tf_e : meye}))

Kernel shape:  (5, 5)
Original Matrix:
 [[1. 3. 3. 4. 5.]
 [7. 5. 1. 6. 1.]
 [3. 4. 1. 9. 2.]
 [8. 6. 2. 6. 5.]
 [6. 4. 5. 2. 7.]]
Rotated Matrix:
 [[6. 8. 3. 7. 1.]
 [4. 6. 4. 5. 3.]
 [5. 2. 1. 1. 3.]
 [2. 6. 9. 6. 4.]
 [7. 5. 2. 1. 5.]]
